# Generated by Django 4.2.28 on 2026-03-03 00:06

import core.fields
import core.utils
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0019_alter_location_code'),
        ('individual', '0020_add_pmt_rerun_right_to_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmtEnrollment',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('pmt_class', models.CharField(choices=[('POOR', 'Poor'), ('NON_POOR', 'Non-Poor')], help_text='PMT classification at time of enrollment', max_length=20)),
                ('pmt_score', models.DecimalField(decimal_places=2, help_text='PMT score at time of enrollment', max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ENROLLED', 'Enrolled in Program'), ('DISENROLLED', 'Disenrolled from Program'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current enrollment status', max_length=20)),
                ('beneficiary_id', models.IntegerField(blank=True, help_text='ID of beneficiary record (if auto-enrolled)', null=True)),
                ('enrollment_date', models.DateTimeField(blank=True, help_text='Date when enrollment was processed', null=True)),
                ('disenrollment_date', models.DateTimeField(blank=True, help_text='Date when disenrollment was processed', null=True)),
                ('disenrollment_reason', models.CharField(blank=True, help_text='Reason for disenrollment (e.g., PMT status changed to NON_POOR)', max_length=255)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', default=dict, help_text='Extended data (e.g., trigger details, approval notes, decision maker info)')),
                ('group', models.ForeignKey(help_text='Household/Group being enrolled', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pmt_enrollments', to='individual.group')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PMT Enrollment',
                'verbose_name_plural': 'PMT Enrollments',
                'ordering': ['-date_created'],
                'managed': True,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PmtConfig',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('pmt_cutoff', models.DecimalField(decimal_places=2, default=11.01, help_text='PMT score cutoff for POOR classification (0-50). Score <= cutoff = POOR', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this PMT config is active for calculations')),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', default=dict, help_text='Extended JSON data (e.g., regional parameters, poverty line thresholds)')),
                ('location', models.OneToOneField(help_text='Location (District or Region) this PMT config applies to', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pmt_config', to='location.location')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PMT Configuration',
                'verbose_name_plural': 'PMT Configurations',
                'managed': True,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPmtEnrollment',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('pmt_class', models.CharField(choices=[('POOR', 'Poor'), ('NON_POOR', 'Non-Poor')], help_text='PMT classification at time of enrollment', max_length=20)),
                ('pmt_score', models.DecimalField(decimal_places=2, help_text='PMT score at time of enrollment', max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ENROLLED', 'Enrolled in Program'), ('DISENROLLED', 'Disenrolled from Program'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current enrollment status', max_length=20)),
                ('beneficiary_id', models.IntegerField(blank=True, help_text='ID of beneficiary record (if auto-enrolled)', null=True)),
                ('enrollment_date', models.DateTimeField(blank=True, help_text='Date when enrollment was processed', null=True)),
                ('disenrollment_date', models.DateTimeField(blank=True, help_text='Date when disenrollment was processed', null=True)),
                ('disenrollment_reason', models.CharField(blank=True, help_text='Reason for disenrollment (e.g., PMT status changed to NON_POOR)', max_length=255)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', default=dict, help_text='Extended data (e.g., trigger details, approval notes, decision maker info)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, help_text='Household/Group being enrolled', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='individual.group')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical PMT Enrollment',
                'verbose_name_plural': 'historical PMT Enrollments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPmtConfig',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('pmt_cutoff', models.DecimalField(decimal_places=2, default=11.01, help_text='PMT score cutoff for POOR classification (0-50). Score <= cutoff = POOR', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this PMT config is active for calculations')),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', default=dict, help_text='Extended JSON data (e.g., regional parameters, poverty line thresholds)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, help_text='Location (District or Region) this PMT config applies to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.location')),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical PMT Configuration',
                'verbose_name_plural': 'historical PMT Configurations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
