# Generated by Django 4.2.30 on 2026-08-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0029_groupindividual_active_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupindividual',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalgroupindividual',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
