# Generated by Django 4.2.30 on 2026-10-09 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('individual', '0032_group_pmt_list_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmtrunprogress',
            name='non_poor_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmtrunprogress',
            name='non_poor_before',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmtrunprogress',
            name='operation',
            field=models.CharField(blank=True, choices=[('RERUN', 'PMT Rerun'), ('CUTOFF_ADJUSTMENT', 'Cutoff Adjustment')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pmtrunprogress',
            name='pmt_cutoff',
            field=models.FloatField(blank=True, help_text='Cutoff applied by this run', null=True),
        ),
        migrations.AddField(
            model_name='pmtrunprogress',
            name='poor_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmtrunprogress',
            name='poor_before',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmtrunprogress',
            name='previous_cutoff',
            field=models.FloatField(blank=True, help_text='District cutoff before this run', null=True),
        ),
        migrations.AddField(
            model_name='pmtrunprogress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
